// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  aboutus: dynamic(() => import("./Aboutus")),
  bento: dynamic(() => import("./Bento")),
  blog: dynamic(() => import("./Blog")),
  blog_page: dynamic(() => import("./BlogPage")),
  call_to_action: dynamic(() => import("./CallToAction")),
  hero: dynamic(() => import("./Hero")),
  integrations: dynamic(() => import("./Integrations")),
  products: dynamic(() => import("./Products")),
  rich_text: dynamic(() => import("./RichText")),
  showcase: dynamic(() => import("./Showcase")),
};
